### ISSUE TITLE
Issue converting cortical imaging file

### ISSUE THREAD

**Issue by ywang-26** [ben-dichter-consulting/jaeger-lab-to-nwb#23]
Hi Ben and Luiz,

Another issue I ran into is with converting cortical imaging file. 

I was using GUI to convert the DIMG2_1001-103 files (shared on the Google Drive - Cortical_Imaging_Cortical_Imaging_Data - DIMG2), .NWB file could not be generated. 

Here is the error I got: 

`/Users/miao/anaconda3/envs/jaeger_nwb/lib/python3.7/site-packages/pynwb/file.py:749: UserWarning: Date is missing timezone information. Updating to local timezone.
  warn("Date is missing timezone information. Updating to local timezone.")
Traceback (most recent call last):
  File "/Users/miao/anaconda3/envs/jaeger_nwb/lib/python3.7/site-packages/nwbn_conversion_tools/gui/nwbn_conversion_gui.py", line 660, in run
    **self.parent.kwargs_fields)
  File "/Users/miao/Programs/jaeger-lab-to-nwb/jaeger_lab_to_nwb/conversion_module.py", line 100, in conversion_function
    dir_cortical_imaging=dir_cortical_imaging
  File "/Users/miao/Programs/jaeger-lab-to-nwb/jaeger_lab_to_nwb/resources/add_ophys.py", line 136, in add_ophys_rsd
    file_rsm_A, files_raw_A, acquisition_date_A, sample_rate_A, n_frames_A = read_trial_meta(trial_meta=trial_meta_A)
  File "/Users/miao/Programs/jaeger-lab-to-nwb/jaeger_lab_to_nwb/resources/add_ophys.py", line 19, in read_trial_meta
    with open(trial_meta, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/miao/Downloads/DIMG2/VSFP_01A0801-103_A.rsh'`

It appears that it was searching for file with prefix VSFP_01A, when the file name is DIMG2_1001-103 ***. 

I am wondering if there is a way to make searching for these files more flexible. Please let me know if more information is needed. 

Thanks!

**Comment by luiztauffer** [comment]
hi @meowater , just to let you know I found the source of this error. 
We're working on refactoring some of the code to comply to the latest updates on nwb-conversion-tools, and a solution for this issue will come with this refactor
